In [11]:
import yaml
import pandas as pd

df = pd.read_csv('area-codes.csv')

ac_list = df['Area Code'].tolist()

print(ac_list)

[201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 212, 213, 214, 215, 216, 217, 218, 219, 224, 225, 226, 228, 229, 231, 234, 239, 240, 242, 246, 248, 250, 251, 252, 253, 254, 256, 260, 262, 264, 267, 268, 269, 270, 276, 281, 284, 289, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 323, 325, 330, 334, 336, 337, 339, 340, 345, 347, 351, 352, 360, 361, 386, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 412, 413, 414, 415, 416, 417, 418, 419, 423, 424, 425, 430, 432, 434, 435, 438, 440, 441, 443, 450, 456, 469, 473, 478, 479, 480, 484, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 512, 513, 514, 515, 516, 517, 518, 519, 520, 530, 540, 541, 551, 559, 561, 562, 563, 567, 570, 571, 573, 574, 580, 585, 586, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 612, 613, 614, 615, 616, 617, 618, 619, 620, 623, 626, 630, 631, 636, 641, 646, 647, 649, 650, 651, 660, 661, 662, 664, 670, 671, 678, 682, 684, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 712, 713, 714, 715, 716, 717, 718, 719, 720, 724, 727, 731, 732, 734, 740, 754, 757, 758, 760, 762, 763, 765, 767, 769, 770, 772, 773, 774, 775, 778, 780, 781, 784, 785, 786, 787, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 812, 813, 814, 815, 816, 817, 818, 819, 828, 829, 830, 831, 832, 843, 845, 847, 848, 850, 856, 857, 858, 859, 860, 862, 863, 864, 865, 866, 867, 868, 869, 870, 876, 877, 878, 888, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 912, 913, 914, 915, 916, 917, 918, 919, 920, 925, 928, 931, 936, 937, 939, 940, 941, 947, 949, 951, 952, 954, 956, 970, 971, 972, 973, 978, 979, 980, 985, 989]

In [17]:
import re

number_test = '''
"2413308066"
"7997551979"
"2682284856"
"6583775915"
"8622320034"
"4581089244"
"4380800922"
"0272765522"
"2312692713"
"5539924675"
"1978517514"
"9416000600"
"3440805483"
"5364170929"
"2991998521"
"3888397109"
"8397644978"
"3401975560"
"9040834120"
"5095743306"
"8964605329"
"6975265876"
"8438119098"
"8369956399"
"9692946960"
"1887286035"
"0622136135"
"2311090443"
"6725559542"
"5270152300"
"4835110551"
"4552585805"
"2170833592"
"2128576437"
"0883549508"
"6617613935"
"3836966581"
"3518614200"
"5365774296"
"6227771821"
"2449754092"
"0976646571"
"1175665683"
"2093494722"
"1832418949"
"3660907325"
"3250753760"
"8826719514"
"6683407178"
"5849820881"
"4029114516"
"1173749933"
"0939878071"
"0066020259"
"2890052844"
"9682103683"
"7668811337"
"8291336406"
"0450849077"
"9547555508"
"3568167630"
"2095383317"
"2427644697"
"1810171593"
"2657083441"
"0654522492"
"3272585526"
"6067775506"
"9705496748"
"6212056349"
"4097202652"
"6789800795"
"6100149092"
"9653485871"
"4871265755"
"9234291050"
"3577943272"
"6845418519"
"2973412785"
"1449105913"
"7838058996"
"4031396226"
"6552909892"
"8056397908"
"1074122384"
"4069464382"
"5196972187"
"8968530625"
"7486645073"
"3304366266"
"4782856022"
"6436356198"
"5414833667"
"2020496858"
"9684510134"
"0709533652"
"2133010657"
"2587358317"
"9251123373"
"9558487763"
"2923190183"
"3412989700"
"2570366525"
"5338463422"
"5920409471"
"5451602714"
"8134179621"
"9278709938"
"6500875732"
'''

area_codes_pattern = '|'.join(map(str, ac_list))

pattern = re.compile(rf'"(?:{area_codes_pattern})\d{7}"')
matches = pattern.finditer(number_test)
for match in matches:
    print(match)

    # WAS LOOKING AT HOW TO MAKE SURE ALL US PHONE NUMBERS THAT ARE 10 DIGITS HAVE THE CORRECT AREA CODES.

In [17]:
import tabula
import pandas as pd

pdf_path = "https://data-handling-public.s3.eu-west-1.amazonaws.com/card_details.pdf"
dfs = tabula.read_pdf(pdf_path, pages='all', stream=True)
dfs = pd.concat(dfs, ignore_index=True)

print(len(dfs))
dfs

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "str"